feat: add support for variable sleep durations
lanrat/homeplate pull request #45
Opened 2024-07-20 14:11 UTC by pimlie

This PR adds support to configure different sleep durations per day-of-week, hour and minute. It should basically support the most common configs as is described in [hass.md](../blob/main/hass.md), so instead of using home-assistant to keep changing the sleep duration it's just baked into the homeplate fw :)

- see `config_example.cpp` for example config
- I had to change the env's a little bit to be able to run the unit tests

2024-08-01 04:46 UTC, lanrat commented on src/config_example.cpp
> +// SleepTimeBlock sleepTimeBlocks[] = {
I do like `sleepIntervals` more than `sleepTimeBlocks`. I also like `sleepSchedule`.

2024-08-01 05:18 UTC, lanrat requested changes
Thanks for the new feature! I left a few very minor nits.

2024-08-01 05:18 UTC, lanrat commented on README.md
> +```cpp
there should be a newline after the text before the code block

2024-08-01 05:18 UTC, lanrat commented on README.md
> +- running them manually
Use `*` for unordered list to stay consistent with the rest of the file

2024-08-01 05:18 UTC, lanrat commented on README.md
> +- in VSCode use Testing -> native -> Run Test
Same as above, use `*` for lists.

2024-08-06 06:02 UTC, lanrat approved these changes

2024-08-06 06:02 UTC, lanrat commented
Thanks for the PR and new feature!

2024-08-06 06:02 UTC, merged

2024-08-18 08:14 UTC, felixh10r commented
@pimlie @lanrat a quick heads-up because it took me a minute to find the problem: in `config_example.h`, `sleep_duration.h` was [renamed](https://github.com/lanrat/homeplate/commit/323ec59266118be3aac48873c3d89cf6640d3ef0#diff-ec67fd79bb9800179eb8f05715869f3faa7e37dc8e717a369cbd4983a986b446R21) to `sleep_schedule.h` but the file wasn't renamed. this line should be reverted, otherwise the correct file can't be found on build (i thought it's more elegant to amend the commit then to open a new PR—if i should, just say the word!)